[tool.poetry]
name = "seminar2"
version = "0.1.0"
description = ""
authors = ["Chesnokov M.A. <chesnokov_ma@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
flask = "^3.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
